all:
	bash ../scripts/create-icns.sh exported/UserCommandServer.png
	mv app.icns exported/UserCommandServer.icns
# Copy files
	cp app.iconset/*.png ../../../Karabiner-Elements-user-command-server/Assets.xcassets/AppIcon.appiconset
	rm -fr app.iconset